[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@host-it/=src/',
    '@host-it-script/=script/',
    '@host-it-test/=test/',
    '@host-it-errors/=src/libs/errors/',
    '@host-it-logs/=src/libs/logs/',
    '@host-it-storage/=src/libs/storage/'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
